### ISSUE TITLE
[Suggestion] Indexing other fields

### ISSUE THREAD

**Issue by jeremyben** [kifuan/json-file-database#3]
Hi, I'm benchmarking typescript json databases, and your project is really well thought out.
Your codebase is also easy to read, which is a huge plus in case of eventual abandonment, which happens a lot in the open source world.
So congrats !

I was wondering if another option could be added to `CollectionOptions` to allow another field than `id` to be indexed ?
And if this index could be made unique or not ?

**Comment by kifuan** [comment]
Certainly. I'm busy these days, but I will find a better way for "reflection" in JS when I'm available.

**Comment by kifuan** [comment]
Support indexing other fields now! See readme for more information.

```ts
const users = db<User>({
  name: 'users',
  primaryKey: 'id',
})
```

However, in my opinion, the primary key should be unique all the time. Using another property is a better choice.

**Comment by jeremyben** [comment]
That was fast, thank you !

But what I meant was indexing **multiple** other keys, other than the primary key (which should be unique of course), so that we don't have the performance penalty for these fields as well.

**Comment by kifuan** [comment]
Umm but the data is stored in sorted array. I think it's hard to have multiple keys when sorting. You can use an object as key with comparator specified, I suppose, like:

_Typing on my mobile phone, you know, hard to format._

```ts
interface A{
  key: { a: number, b: string }
}

db<A>({
name: 'a', comparator: (first, second) => {...}
})
```

**Comment by jeremyben** [comment]
Yes you're absolutely right, I forgot about the sorted part that makes the binary search works.
